spring:
  datasource:
    url: ${URL}
    username: ${USER}
    password: ${PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    locations: ${MIGRATIONS_PATH}
server:
  port: ${PORT:8080}
  address: 0.0.0.0
springdoc:
  swagger-ui:
    path: /docs